apiVersion: apps/v1
kind: Deployment
metadata: # Dictionary
  name: myapp1-deployment
spec: # Dictionary
  replicas: 2
  selector:
    matchLables:
      app: myapp1
  template:
    metadata: # Dictionary
     name: myapp1-pod
     lables: # Dictionary
       app: myapp1 # Key Value Pairs
    spec:
      containers: # List
        - name: myapp1-container
          image: stacksimplify/kubenginx:1.0.0
          ports: 
            - containerPort: 80  